import express from "express";
import path from "path";
import fs from "fs";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";
import QRCode from "qrcode";
import AdmZip from "adm-zip";
import { GoogleGenAI } from "@google/genai";

// Load configurations
dotenv.config();

import { getConfig, updateConfig } from "./src/bot/config.js";
import { initRegistry, getCommands, registerCommand, getCommand } from "./src/bot/commandRegistry.js";
import { getBotState, startLiveBot, stopLiveBot, addLog, simulateMessage, clearLogs } from "./src/bot/botEngine.js";
import { getCommandStats } from "./src/bot/commandStats.js";
import { getAIClient, generateTextWithFallback } from "./src/bot/geminiClient.js";

// Initialize command registry
initRegistry();

const app = express();
const PORT = 3000;

app.use(express.json());

// API: Get and Update Configuration
app.get("/api/bot/config", (req, res) => {
  res.json(getConfig());
});

app.post("/api/bot/config", (req, res) => {
  const newConfig = req.body;
  const updated = updateConfig(newConfig);
  addLog(`⚙️ Configuration updated from panel: Bot Name: "${updated.botName}", Prefix: "${updated.prefix}"`);
  res.json(updated);
});

// API: Get Connection State & QR Code
app.get("/api/bot/status", (req, res) => {
  res.json(getBotState());
});

app.get("/api/bot/qr", async (req, res) => {
  const { qrCode } = getBotState();
  if (!qrCode) {
    return res.status(404).json({ error: "No active QR code. Start the live connection first." });
  }
  try {
    const qrUrl = await QRCode.toDataURL(qrCode, { margin: 2, width: 250 });
    res.json({ qrUrl });
  } catch (error: any) {
    res.status(500).json({ error: "Failed to generate QR code image." });
  }
});

// API: Start / Stop Live Bot
app.post("/api/bot/start", (req, res) => {
  startLiveBot();
  res.json({ success: true, message: "Live bot start triggered." });
});

app.post("/api/bot/stop", (req, res) => {
  stopLiveBot();
  res.json({ success: true, message: "Live bot stop triggered." });
});

// API: Clear Logs
app.post("/api/bot/clear-logs", (req, res) => {
  clearLogs();
  res.json({ success: true });
});

// API: Command Simulation Playground
app.post("/api/bot/simulate", async (req, res) => {
  const { senderName, text } = req.body;
  if (!text) {
    return res.status(400).json({ error: "Message text is required." });
  }
  const result = await simulateMessage(senderName || "Guest User", text);
  res.json(result);
});

// API: List Commands
app.get("/api/bot/commands", (req, res) => {
  const commands = getCommands().map(cmd => ({
    name: cmd.name,
    category: cmd.category,
    description: cmd.description,
    usage: cmd.usage || cmd.name,
    aliases: cmd.aliases || [],
  }));
  res.json(commands);
});

// API: Get command usage analytics
app.get("/api/bot/analytics", (req, res) => {
  res.json({ stats: getCommandStats() });
});

// API: Get details or code of a single command
app.get("/api/bot/commands/:name", (req, res) => {
  const cmdName = req.params.name.toLowerCase();
  const cmd = getCommand(cmdName);
  if (!cmd) {
    return res.status(404).json({ error: "Command not found." });
  }

  // Attempt to read the physical code file
  const commandsDir = path.join(process.cwd(), "src", "bot", "commands");
  const filePath = path.join(commandsDir, `${cmdName}.ts`);
  
  let code = "";
  if (fs.existsSync(filePath)) {
    code = fs.readFileSync(filePath, "utf-8");
  } else {
    // Return structured representation if file not on disk
    code = `import { BotCommand } from "../types.js";\n\n// Autogenerated dynamic code fallback\nconst cmd: BotCommand = {\n  name: "${cmd.name}",\n  category: "${cmd.category}",\n  description: "${cmd.description}",\n  execute: async (sock, msg, context) => {\n    await context.reply("Hello from ${cmd.name}!");\n  }\n};\nexport default cmd;`;
  }

  res.json({
    ...cmd,
    code
  });
});

// API: Save or Create a command file
app.post("/api/bot/commands/save", (req, res) => {
  const { name, code, category, description } = req.body;
  if (!name || !code) {
    return res.status(400).json({ error: "Name and code are required." });
  }

  const cleanName = name.trim().toLowerCase().replace(/[^a-z0-9]/g, "");
  const commandsDir = path.join(process.cwd(), "src", "bot", "commands");
  
  if (!fs.existsSync(commandsDir)) {
    fs.mkdirSync(commandsDir, { recursive: true });
  }

  const filePath = path.join(commandsDir, `${cleanName}.ts`);
  
  try {
    fs.writeFileSync(filePath, code, "utf-8");
    addLog(`📝 Saved command file: /src/bot/commands/${cleanName}.ts`);

    // Reload the registry
    initRegistry();
    res.json({ success: true, message: `Command ${cleanName} saved and loaded.` });
  } catch (error: any) {
    res.status(500).json({ error: `Failed to save command: ${error.message}` });
  }
});

// API: AI-Powered Command Builder (using Gemini 3.7-flash)
app.post("/api/bot/commands/generate", async (req, res) => {
  const { prompt, commandName, category, description } = req.body;
  
  if (!prompt || !commandName) {
    return res.status(400).json({ error: "Prompt and commandName are required." });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || apiKey === "MY_GEMINI_API_KEY" || apiKey.trim() === "") {
    return res.status(400).json({ error: "Gemini API key is not configured. Please add it to Settings > Secrets." });
  }

  const cleanName = commandName.trim().toLowerCase().replace(/[^a-z0-9]/g, "");
  const cleanCategory = (category || "Utility").trim();
  const cleanDesc = (description || `Dynamic AI-generated command for ${cleanName}`).trim();

  addLog(`🤖 Asking Gemini to design command: "${cleanName}" (${prompt})`);

  try {
    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });

    const aiPrompt = `
Generate a fully functional TypeScript WhatsApp command file for a Baileys bot.
The file must export a default object implementing the following interface:

interface BotCommand {
  name: string;
  category: string;
  description: string;
  usage?: string;
  execute: (sock: any, msg: any, context: {
    sender: string;
    senderName: string;
    isOwner: boolean;
    prefix: string;
    commandName: string;
    args: string[];
    fullMessage: string;
    reply: (text: string, mediaUrl?: string) => Promise<any>;
    react: (emoji: string) => Promise<any>;
    downloadMedia?: () => Promise<Buffer | null>;
  }) => Promise<void> | void;
}

The command name is: "${cleanName}"
The category is: "${cleanCategory}"
The description is: "${cleanDesc}"
Specific instructions for what the command should do: "${prompt}"

Make the logic clean, fully typed, and robust. Always use markdown formatting in text outputs for neat messaging layout (e.g. bold like *text*, italics like _text_). If you use external API fetches, handle errors cleanly with try-catch and output helpful error messages. Use standard ES Module imports, specifically relative importing of the BotCommand type if needed, e.g. import { BotCommand } from "../types.js";

IMPORTANT: Output ONLY the raw TypeScript code. No markdown wrapping (like \`\`\`typescript ... \`\`\`), no conversational intros. Just raw TS code so I can save it directly to a file.
`;

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents: aiPrompt,
    });

    let code = response.text || "";
    
    // Safety: strip markdown wraps if Gemini returned them despite instructions
    if (code.includes("```typescript")) {
      code = code.split("```typescript")[1].split("```")[0];
    } else if (code.includes("```ts")) {
      code = code.split("```ts")[1].split("```")[0];
    } else if (code.includes("```")) {
      code = code.split("```")[1].split("```")[0];
    }
    
    code = code.trim();

    // Save the file
    const commandsDir = path.join(process.cwd(), "src", "bot", "commands");
    if (!fs.existsSync(commandsDir)) {
      fs.mkdirSync(commandsDir, { recursive: true });
    }
    const filePath = path.join(commandsDir, `${cleanName}.ts`);
    fs.writeFileSync(filePath, code, "utf-8");

    // Re-initialize registry
    initRegistry();
    addLog(`✨ AI generated & successfully loaded command: /src/bot/commands/${cleanName}.ts`);

    res.json({
      success: true,
      message: `Command "${cleanName}" created successfully!`,
      code,
    });
  } catch (error: any) {
    addLog(`❌ AI Command Generation failed: ${error.message}`);
    res.status(500).json({ error: `AI generation failed: ${error.message}` });
  }
});

// API: Download complete ready-to-run bot package as a ZIP!
app.get("/api/bot/download-zip", (req, res) => {
  addLog("📦 Packaging Nebula Bot for local download...");
  const config = getConfig();
  
  try {
    const zip = new AdmZip();

    // 1. Generate local start file: index.js
    const indexJs = `/**
 * Nebula Bot Local Startup File
 * Powered by @whiskeysockets/baileys
 */

const { default: makeWASocket, useMultiFileAuthState, DisconnectReason, fetchLatestBaileysVersion } = require("@whiskeysockets/baileys");
const pino = require("pino");
const { Boom } = require("@hapi/boom");
const dotenv = require("dotenv");
const path = require("path");
const fs = require("fs");

dotenv.config();

const config = require("./config.json");

// Command Registry
const commands = new Map();

function loadCommands() {
  const commandsDir = path.join(__dirname, "commands");
  if (!fs.existsSync(commandsDir)) return;
  
  const files = fs.readdirSync(commandsDir);
  for (const file of files) {
    if (!file.endsWith(".js")) continue;
    try {
      const cmdPath = path.join(commandsDir, file);
      delete require.cache[require.resolve(cmdPath)];
      const cmd = require(cmdPath);
      // Support both ES default and CJS exports
      const command = cmd.default || cmd;
      if (command && command.name) {
        commands.set(command.name.toLowerCase(), command);
        console.log(\`🔮 Loaded command: \${command.name}\`);
      }
    } catch (err) {
      console.error(\`❌ Failed to load command file \${file}:\`, err.message);
    }
  }
  // Expose registered commands list globally for menu
  global.botCommands = Array.from(commands.values());
}

async function startBot() {
  console.log("🌌 Starting Nebula Bot...");
  loadCommands();

  const { state, saveCreds } = await useMultiFileAuthState("auth_session");
  const { version } = await fetchLatestBaileysVersion();

  const sock = makeWASocket({
    version,
    auth: state,
    printQRInTerminal: true, // Output QR in terminal for easy local scanning
    logger: pino({ level: "info" }),
    browser: ["Nebula Local", "Chrome", "1.0.0"],
  });

  sock.ev.on("connection.update", (update) => {
    const { connection, lastDisconnect, qr } = update;
    if (connection === "open") {
      console.log("✅ Nebula Bot connected successfully! Type .menu in chat to start.");
    }
    if (connection === "close") {
      const shouldReconnect = (lastDisconnect.error instanceof Boom) ? lastDisconnect.error.output.statusCode !== DisconnectReason.loggedOut : true;
      console.log(\`❌ Connection closed. Reconnecting: \${shouldReconnect}\`);
      if (shouldReconnect) {
        startBot();
      }
    }
  });

  sock.ev.on("creds.update", saveCreds);

  sock.ev.on("messages.upsert", async (m) => {
    if (m.type !== "notify") return;
    for (const msg of m.messages) {
      if (!msg.message || msg.key.fromMe) continue;

      const text = msg.message.conversation || 
                   msg.message.extendedTextMessage?.text || 
                   msg.message.imageMessage?.caption || 
                   msg.message.videoMessage?.caption || 
                   "";

      const prefix = config.prefix;
      if (!text.startsWith(prefix)) continue;

      const senderJid = msg.key.remoteJid;
      const senderNumber = senderJid.split("@")[0];
      const senderName = msg.pushName || "User";

      const body = text.slice(prefix.length).trim();
      const args = body.split(/\\s+/);
      const commandName = args.shift().toLowerCase();

      const command = commands.get(commandName);
      if (!command) continue;

      const isOwner = senderNumber === config.ownerNumber.replace(/[^0-9]/g, "");

      const context = {
        sender: senderJid,
        senderName,
        isOwner,
        prefix,
        commandName,
        args,
        fullMessage: text,
        reply: async (textStr, mediaUrl) => {
          if (mediaUrl) {
            return await sock.sendMessage(senderJid, { image: { url: mediaUrl }, caption: textStr }, { quoted: msg });
          }
          return await sock.sendMessage(senderJid, { text: textStr }, { quoted: msg });
        },
        react: async (emoji) => {
          return await sock.sendMessage(senderJid, { react: { text: emoji, key: msg.key } });
        }
      };

      try {
        await command.execute(sock, msg, context);
      } catch (err) {
        console.error(\`Error in \${commandName}:\`, err);
        context.reply(\`❌ Error in \${commandName}: \` + err.message);
      }
    }
  });
}

startBot();
`;

    // 2. Generate package.json for local
    const packageJson = {
      name: "nebula-bot-local",
      version: "1.0.0",
      description: "Nebula Bot - Lightweight WhatsApp Multi-Device Bot",
      main: "index.js",
      scripts: {
        start: "node index.js",
      },
      dependencies: {
        "@whiskeysockets/baileys": "^6.7.9",
        "@hapi/boom": "^10.0.1",
        "pino": "^9.0.0",
        "dotenv": "^16.4.5",
        "qrcode-terminal": "^0.12.0",
        "@google/genai": "^2.4.0"
      }
    };

    // 3. Generate README.md
    const readmeMd = `# 🌌 Nebula Bot - WhatsApp Multi-Device

A highly lightweight and modular WhatsApp Multi-Device Bot.

## 🚀 Quick Local Installation

1. Make sure you have **Node.js 18 or newer** installed.
2. Extract the downloaded ZIP file into a clean folder.
3. Open your terminal in the extracted folder and run:
   \`\`\`bash
   npm install
   \`\`\`
4. Configure your environment variables in \`.env\`:
   \`\`\`env
   GEMINI_API_KEY="YOUR_API_KEY_HERE"
   \`\`\`
5. Start the bot:
   \`\`\`bash
   npm start
   \`\`\`
6. A WhatsApp QR Code will print in your terminal. Scan it using **Linked Devices** on your phone!

## 🔮 Customization & Commands

- **Config File:** Edit \`config.json\` to customize prefix, bot name, bot image, and channel details.
- **Add Features:** All commands are loaded dynamically from the \`commands/\` folder. To create a new command, just add a new \`.js\` file into the \`commands/\` folder exporting a command structure!
`;

    // Add files to Zip
    zip.addFile("index.js", Buffer.from(indexJs), "Main local runner");
    zip.addFile("package.json", Buffer.from(JSON.stringify(packageJson, null, 2)), "Dependencies list");
    zip.addFile("config.json", Buffer.from(JSON.stringify(getConfig(), null, 2)), "Custom configuration settings");
    zip.addFile("README.md", Buffer.from(readmeMd), "Documentation");
    
    // Add environment template
    const localEnv = `GEMINI_API_KEY="${process.env.GEMINI_API_KEY || "MY_GEMINI_API_KEY"}"\n`;
    zip.addFile(".env", Buffer.from(localEnv), "Environment configuration");

    // Copy command files into ZIP (convert typescript files to node-ready ESM or CJS if needed, or simply package the commands directly)
    const commandsDir = path.join(process.cwd(), "src", "bot", "commands");
    if (fs.existsSync(commandsDir)) {
      const files = fs.readdirSync(commandsDir);
      for (const file of files) {
        if (!file.endsWith(".ts")) continue;
        const filePath = path.join(commandsDir, file);
        let fileContent = fs.readFileSync(filePath, "utf-8");
        
        // Convert typical typescript imports/exports to make them raw Node compatible in the export!
        // To keep it simple, we can keep them in JS format or standard CommonJS for absolute execution.
        // Let's translate some key lines like 'export default' and 'import' to clean ES/CommonJS if they are standard.
        // A simple JS translation for the zip output ensures Node runs it with ZERO compilation!
        let jsContent = fileContent
          .replace(/import\s+(\w+)\s+from\s+['"]\.\.\/types\.js['"];?/g, "")
          .replace(/import\s+\{\s*BotCommand\s*\}\s+from\s+['"]\.\.\/types\.js['"];?/g, "")
          .replace(/import\s+\{\s*getConfig,\s*updateConfig\s*\}\s+from\s+['"]\.\.\/config\.js['"];?/g, "const config = require('../config.json');\nconst getConfig = () => config;\nconst updateConfig = () => {};")
          .replace(/import\s+({.*})\s+from\s+["']@google\/genai["']/g, "const { GoogleGenAI } = require('@google/genai')")
          .replace(/import\s+({.*})\s+from\s+["'](.*)["']/g, "const $1 = require('$2')")
          .replace(/export\s+default\s+(\w+);?/g, "module.exports = $1;")
          .replace(/const\s+(\w+):\s*BotCommand\s*=/g, "const $1 =")
          .replace(/:\s*BotCommand/g, "");

        zip.addFile(`commands/${file.replace(".ts", ".js")}`, Buffer.from(jsContent), "Command logic file");
      }
    }

    const zipBuffer = zip.toBuffer();
    
    res.set({
      "Content-Type": "application/zip",
      "Content-Disposition": "attachment; filename=nebula-bot-local.zip",
      "Content-Length": zipBuffer.length
    });

    res.send(zipBuffer);
    addLog("✅ Nebula Bot ZIP compiled and sent to user successfully!");
  } catch (error: any) {
    addLog(`❌ Failed to compile ZIP download: ${error.message}`);
    res.status(500).json({ error: `ZIP packing failed: ${error.message}` });
  }
});

// API: Audio Transcription using Gemini with fallback models
app.post("/api/gemini/transcribe", async (req, res) => {
  const { audioBase64, mimeType } = req.body;
  if (!audioBase64) {
    return res.status(400).json({ error: "Missing audioBase64 payload" });
  }

  const ai = getAIClient();
  if (!ai) {
    return res.status(400).json({ error: "Gemini API key is not configured. Please add it to Settings > Secrets." });
  }

  const transcriptionModels = ["gemini-3.5-flash", "gemini-2.5-flash", "gemini-1.5-flash"];
  let lastError: any = null;

  for (const model of transcriptionModels) {
    try {
      const response = await ai.models.generateContent({
        model,
        contents: [
          {
            inlineData: {
              data: audioBase64,
              mimeType: mimeType || "audio/webm",
            },
          },
          { text: "Accurately transcribe this audio message. Output only the plain transcription, no extra commentary, preambles, or punctuation headers." },
        ],
      });

      if (response && response.text) {
        return res.json({ transcript: response.text.trim() });
      }
    } catch (err: any) {
      console.warn(`⚠️ Transcription failed on model [${model}]:`, err?.message || err);
      lastError = err;
    }
  }

  res.status(500).json({ error: `Transcription failed across all fallback models: ${lastError?.message || lastError}` });
});

// API: Real-time Voice Conversation using Gemini with fallbacks and TTS
app.post("/api/gemini/voice-conversation", async (req, res) => {
  const { prompt } = req.body;
  if (!prompt) {
    return res.status(400).json({ error: "Missing prompt query" });
  }

  const ai = getAIClient();
  if (!ai) {
    return res.status(400).json({ error: "Gemini API key is not configured. Please add it to Settings > Secrets." });
  }

  try {
    // 1. Generate textual spoken reply using robust text fallback generator helper
    const replyText = await generateTextWithFallback(
      prompt,
      "You are a friendly, helpful, highly conversational AI voice assistant. Keep your responses super short (1-2 sentences), sweet, warm, and direct. Avoid asterisks, bullets, lists, markdown formatting, or emojis since your response will be read aloud.",
      "gemini-3.5-flash"
    );

    // 2. Synthesize spoken reply to audio using TTS preview model
    let audioBase64: string | null = null;
    try {
      const speechResponse = await ai.models.generateContent({
        model: "gemini-3.1-flash-tts-preview",
        contents: [{ parts: [{ text: replyText }] }],
        config: {
          responseModalities: ["AUDIO"],
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: "Zephyr" },
            },
          },
        },
      });
      audioBase64 = speechResponse.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data || null;
    } catch (ttsErr: any) {
      console.warn("⚠️ TTS audio synthesis rate-limited or busy. Falling back to text-only spoken reply.", ttsErr?.message || ttsErr);
    }

    res.json({
      text: replyText,
      audioBase64
    });
  } catch (error: any) {
    console.error("Voice conversation error:", error);
    res.status(500).json({ error: error.message || error });
  }
});

// Start dev server with Vite in full-stack mode
async function startServer() {
  // Vite dev server middleware setup
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    addLog(`🚀 Nebula Controller Panel is live on http://localhost:${PORT}`);
  });
}

startServer();
